"""Merge data/parts/*.json -> data/prompts.json and data/prompts.js, with validation."""
import glob
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PARTS = sorted(glob.glob(os.path.join(ROOT, "data", "parts", "*.json")))
PH = re.compile(r"\{\{(.+?)\}\}")
LABELS = ("[역할]", "[업무 배경]", "[요청 사항]", "[출력 형식]")


def sort_key(p):
    a, b = p["id"].split("-")
    return (int(a), int(b))


items = []
for f in PARTS:
    with open(f, encoding="utf-8") as fh:
        items.extend(json.load(fh))
items.sort(key=sort_key)

errors = []
ids = [p["id"] for p in items]
dupes = sorted({i for i in ids if ids.count(i) > 1})
if dupes:
    errors.append(f"duplicate ids: {dupes}")

for p in items:
    tpl_keys = []
    for m in PH.finditer(p["template"]):
        if m.group(1) not in tpl_keys:
            tpl_keys.append(m.group(1))
    field_keys = [f["key"] for f in p["fields"]]
    if set(tpl_keys) != set(field_keys):
        only_tpl = sorted(set(tpl_keys) - set(field_keys))
        only_fields = sorted(set(field_keys) - set(tpl_keys))
        errors.append(f"{p['id']}: template-only {only_tpl} / fields-only {only_fields}")
    if len(field_keys) != len(set(field_keys)):
        errors.append(f"{p['id']}: duplicate field keys")
    for req in ("title", "template", "partTitle"):
        if not str(p.get(req, "")).strip():
            errors.append(f"{p['id']}: empty {req}")
    if not (1 <= int(p["part"]) <= 7):
        errors.append(f"{p['id']}: bad part {p['part']}")
    if "\t" in p["template"]:
        errors.append(f"{p['id']}: tab in template")
    for lab in LABELS:
        if lab not in p["template"]:
            errors.append(f"{p['id']}: missing section label {lab}")

print(f"prompts: {len(items)}")
if errors:
    print("VALIDATION ERRORS:")
    for e in errors:
        print(" -", e)
    sys.exit(1)

with open(os.path.join(ROOT, "data", "prompts.json"), "w", encoding="utf-8") as fh:
    json.dump(items, fh, ensure_ascii=False, indent=2)
with open(os.path.join(ROOT, "data", "prompts.js"), "w", encoding="utf-8") as fh:
    fh.write("// generated by scripts/build-data.py - do not edit; edit data/parts/*.json\n")
    fh.write("window.PROMPTS = " + json.dumps(items, ensure_ascii=False) + ";\n")
print("ok -> data/prompts.json, data/prompts.js")
